services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qrcode-api
    ports:
      - "5000:5000"
      - "9000:9000"
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
      FLASK_SECRET_KEY: your_secret_key_here
      DATABASE_URL: postgresql://postgres:postgr3s@db:5432/localdb
      CORS_ORIGINS: http://localhost:5173,http://localhost:8000
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - "${HOME}/Documents/salida:/app/salida"
    networks:
      - qrcode-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qrcode
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - qrcode-network

  db:
    image: postgres:15
    container_name: qrcode-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgr3s
      POSTGRES_DB: localdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qrcode-network

  redis:
    image: redis:alpine
    container_name: dinqr-redis
    ports:
      - "6379:6379"
    networks:
      - qrcode-network

volumes:
  postgres_data:

networks:
  qrcode-network:
    driver: bridge