"""Agregar tablas de control de prestadores

Revision ID: 17a0055a5687
Revises: 4063c09db320
Create Date: 2025-11-12 16:09:19.627665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a0055a5687'
down_revision = '4063c09db320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areaservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centroneg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiposervice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('filiacao', sa.String(length=100), nullable=True),
    sa.Column('data_nas', sa.Date(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('nacionalidade', sa.String(length=25), nullable=True),
    sa.Column('bi_pass', sa.String(length=20), nullable=True),
    sa.Column('emissao', sa.Date(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('local_resid', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial',
    sa.Column('id_hist', sa.Integer(), nullable=False),
    sa.Column('id_prest', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_centro_neg', sa.Integer(), nullable=False),
    sa.Column('id_funcao', sa.Integer(), nullable=False),
    sa.Column('data_ini_prest', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=True),
    sa.Column('data_fim_prest', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('id_tipo_servico', sa.Integer(), nullable=False),
    sa.Column('id_local_serv', sa.Integer(), nullable=False),
    sa.Column('andar', sa.String(length=10), nullable=True),
    sa.Column('conflito', sa.Boolean(), nullable=True),
    sa.Column('quando', sa.Date(), nullable=True),
    sa.Column('motivo_conflito', sa.String(length=100), nullable=True),
    sa.Column('id_areas', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_areas'], ['areaservice.id'], ),
    sa.ForeignKeyConstraint(['id_centro_neg'], ['centroneg.id'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_funcao'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['id_local_serv'], ['localservice.id'], ),
    sa.ForeignKeyConstraint(['id_prest'], ['prestadores.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_servico'], ['tiposervice.id'], ),
    sa.PrimaryKeyConstraint('id_hist')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    op.drop_table('prestadores')
    op.drop_table('tiposervice')
    op.drop_table('localservice')
    op.drop_table('locales')
    op.drop_table('functions')
    op.drop_table('empresas')
    op.drop_table('centroneg')
    op.drop_table('areaservice')
    # ### end Alembic commands ###
